### ISSUE TITLE
Aprender comandos do Git.

### ISSUE THREAD

**Issue by leomitx10** [davialvb/Feudo-Vermelho-Rosas#10]
### Descrição:
Aprender comandos do Git.

### Tarefas
- [ ] Assistir os 2 vídeos.

### Videos
Rafaella Ballerini Git
https://www.youtube.com/watch?v=UBAX-13g8OM&t=1218s

### Critérios de Aceitação
- [ ] Fazer uma documentação descrevendo o que cada comando faz.

**Comment by leomitx10** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feudo-Vermelho-Rosas-61fb35ef8e4d7500100d5684/issues/davialvb/Feudo-Vermelho-Rosas/10?planning-poker) with ZenHub @GustavoFBS @flavioovatsug @davialvb

**Comment by flavioovatsug** [comment]
Rafaella Ballerini Git
https://www.youtube.com/watch?v=UBAX-13g8OM&t=1218s
