### ISSUE TITLE
Aprender JS

### ISSUE THREAD

**Issue by leomitx10** [davialvb/Feudo-Vermelho-Rosas#7]
### Descrição:
Aprender JS para criar um menu.

### Tarefas
- [ ] Aprender estrutura de dados
- [ ] Aprender Entrada e saída 
- [ ] Aprender vetores
- [ ] Aprender estrutura de repetição
- [ ] Funções
- [ ] Condicionais

### Critérios de Aceitação
- [ ] Fazer uma documentação sobre o que aprendeu.

**Comment by leomitx10** [comment]
### Descrição:
Aprender JS para criar um menu.

### Tarefas
- [ ] Aprender estrutura de dados
- [ ] Aprender Entrada e saída 
- [ ] Aprender vetores
- [ ] Aprender estrutura de repetição
- [ ] Funções
- [ ] Condicionais

### Critérios de Aceitação
- [ ] Fazer uma documentação sobre o que aprendeu.

**Comment by leomitx10** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Feudo-Vermelho-Rosas-61fb35ef8e4d7500100d5684/issues/davialvb/Feudo-Vermelho-Rosas/7?planning-poker) with ZenHub @GustavoFBS @flavioovatsug @davialvb

**Comment by flavioovatsug** [comment]
Uau
